version: "3.8"

services:
  pgcurriculo:
    image: postgres:17.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: pgcurriculo
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped 
  
  curriculo_api:
    build:
      dockerfile: ./docker/curriculo.dockerfile
      context: .
    container_name: curriculo_api
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver ${DJANGO_BASE_URL}:${DJANGO_PORT}"
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - pgcurriculo
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app

  # cloudflared-tunnel:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared-tunnel
  #   restart: unless-stopped
  #   volumes:
  #     # Monta o diretório de credenciais dentro do container
  #     - ./.cloudflared:/home/nonroot/.cloudflared
  #   command: tunnel --no-autoupdate run curriculo-prod

volumes:
  pgdata:
