# Generated by Django 4.1.1 on 2022-09-27 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('inicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Ano início')),
                ('fim', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Ano fim')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Educação',
                'verbose_name_plural': 'Educação',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('inicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Ano início')),
                ('fim', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Ano fim')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.CharField(choices=[('fa fa-2x fa-laptop service-icon bg-primary text-white mr-3', 'Laptop'), ('fa fa-2x fa-laptop-code service-icon bg-primary text-white mr-3', 'Laptop-code'), ('fab fa-2x fa-android service-icon bg-primary text-white mr-3', 'Android'), ('fab fa-2x fa-apple service-icon bg-primary text-white mr-3', 'Apple'), ('fa fa-2x fa-search service-icon bg-primary text-white mr-3', 'Search'), ('fa fa-2x fa-edit service-icon bg-primary text-white mr-3', 'Edit'), ('fa fa-2x fa-solid fa-robot service-icon bg-primary text-white mr-3', 'Robot'), ('fa fa-2x fa-solid fa-bolt service-icon bg-primary text-white mr-3', 'lightning')], max_length=100, verbose_name='Icone'),
        ),
    ]
