# Generated by Django 4.1.1 on 2022-09-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.CharField(choices=[('fa fa-2x fa-laptop service-icon bg-primary text-white mr-3', 'Laptop'), ('fa fa-2x fa-laptop-code service-icon bg-primary text-white mr-3', 'Laptop-code'), ('fab fa-2x fa-android service-icon bg-primary text-white mr-3', 'Android'), ('fab fa-2x fa-apple service-icon bg-primary text-white mr-3', 'Apple'), ('fa fa-2x fa-search service-icon bg-primary text-white mr-3', 'Search'), ('fa fa-2x fa-edit service-icon bg-primary text-white mr-3', 'Edit')], max_length=100, verbose_name='Icone'),
        ),
    ]
