# Generated by Django 4.1.1 on 2022-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='escolaridade',
            field=models.TextField(max_length=35, verbose_name='Escolariade'),
        ),
    ]
