# Generated by Django 4.1.1 on 2022-09-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sobre_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='escolaridade',
            field=models.TextField(max_length=45, verbose_name='Escolariade'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='nome',
            field=models.CharField(max_length=40, verbose_name='Nome'),
        ),
    ]
