# Generated by Django 4.1.1 on 2022-09-27 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='fim',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Ano fim'),
        ),
        migrations.AlterField(
            model_name='education',
            name='inicio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Ano início'),
        ),
    ]
