# Generated by Django 4.1.1 on 2022-09-29 19:24

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 600, 'width': 600}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Foto Header',
                'verbose_name_plural': 'Fotos Header',
            },
        ),
    ]
