# Generated by Django 4.1.1 on 2022-09-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_education_fim_alter_education_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Educação', 'verbose_name_plural': 'Educação'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
    ]
