# Generated by Django 4.1.1 on 2022-10-05 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_headerpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('porcentagem', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem')),
                ('cor', models.CharField(choices=[('progress-bar bg-primary', 'Verde'), ('progress-bar bg-warning', 'Amarelo'), ('progress-bar bg-danger', 'Vermelho'), ('progress-bar bg-dark', 'Preto'), ('font-weight-bold', 'Azul')], max_length=100, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
    ]
