# Generated by Django 4.1.1 on 2022-10-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projetos_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='tag',
        ),
        migrations.AddField(
            model_name='projetos',
            name='tag',
            field=models.ManyToManyField(to='core.filtrosprojetos'),
        ),
    ]
