# Generated by Django 4.1.1 on 2022-10-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_education_descricao_en_education_descricao_pt_br_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='competencia_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Competência'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='competencia_pt_br',
            field=models.CharField(max_length=40, null=True, verbose_name='Competência'),
        ),
        migrations.AddField(
            model_name='experience',
            name='descricao_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='experience',
            name='descricao_pt_br',
            field=models.TextField(max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='experience',
            name='subtitulo_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='experience',
            name='subtitulo_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='experience',
            name='titulo_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='experience',
            name='titulo_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='service',
            name='descricao_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='service',
            name='descricao_pt_br',
            field=models.TextField(max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='service',
            name='servico_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='service',
            name='servico_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='descricao_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='descricao_pt_br',
            field=models.TextField(max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='escolaridade_en',
            field=models.TextField(max_length=45, null=True, verbose_name='Escolariade'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='escolaridade_pt_br',
            field=models.TextField(max_length=45, null=True, verbose_name='Escolariade'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='titulo_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='titulo_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
    ]
