# Generated by Django 4.1.1 on 2025-08-04 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_experience_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='education',
            name='descricao_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='education',
            name='descricao_pt_br',
            field=models.TextField(max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='education',
            name='fim',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Ano fim'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='descricao_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='descricao_pt_br',
            field=models.TextField(max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='fim',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Ano fim'),
        ),
    ]
