# Generated by Django 4.1.1 on 2025-08-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_education_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='descricao_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='descricao_pt_br',
            field=models.TextField(max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='escolaridade',
            field=models.TextField(max_length=150, verbose_name='Escolariade'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='escolaridade_en',
            field=models.TextField(max_length=150, null=True, verbose_name='Escolariade'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='escolaridade_pt_br',
            field=models.TextField(max_length=150, null=True, verbose_name='Escolariade'),
        ),
    ]
