"""
Django settings for curriculo project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os.path
from pathlib import Path

from dj_database_url import parse as psql_url

from decouple import config

from django.contrib.messages import constants as messages

import django.core.mail.backends.base

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')
ADMIN_PATH = config('ADMIN_PATH') 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])

# Application definition

INSTALLED_APPS = [
    'core',

    'modeltranslation',
    'admin_honeypot',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Ajuda a automatizar a detecção de linguagem através do navegador
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'curriculo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'curriculo.wsgi.application'

ADMINS = [
    (config('ADMIN_NAME'), config('ADMIN_EMAIL')),
]

ADMIN_HONEYPOT_EMAIL_ADMINS = True

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('POSTGRES_DB'),
#         'USER': config('POSTGRES_USER'),
#         'PASSWORD': config('POSTGRES_PASSWORD'),
#         'HOST': 'pgcurriculo',  # nome do serviço no docker-compose
#         'PORT': config('POSTGRES_PORT', default='5432'),
#     }
# }

DATABASES = {
    'default': config(
        'POSTGRES_URL',
        cast=psql_url
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# MUITO IMPORTANTE: O MEDIA_URL agora será um caminho relativo.
# O Nginx irá interceptar esse caminho e buscar o conteúdo no MinIO.
# Ele não contém mais o domínio.
MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# MEDIA_URL = f"{config('AWS_S3_ENDPOINT_URL')}/{config('AWS_STORAGE_BUCKET_NAME')}/"

STORAGES = {
    # Backend para arquivos de mídia (uploads dos usuários)
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    # Em produção, o Nginx servirá os estáticos.
    # Mas deixar isso aqui não atrapalha e funciona bem em dev.
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Configurações S3/MinIO
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')  # ex.: "http://minio:9000" no docker ou "http://localhost:9000"
AWS_S3_REGION_NAME = None  # MinIO não exige região
AWS_QUERYSTRING_AUTH = False # True para usar presigned URLs # Mude para False. O Nginx agora controla o acesso.
AWS_QUERYSTRING_EXPIRE = 3600  # tempo em segundos que a URL presigned vai valer

# === ADICIONE ESTA LINHA PARA CORRIGIR AS URLS ===
AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN')
AWS_S3_URL_PROTOCOL = 'http:'
# AWS_S3_URL_PROTOCOL = 'https:' 

# Constrói o URL base para seus arquivos de mídia. Ex: localhost:9000/django-curriculo o Nginx cuidará do domínio.
# AWS_S3_ADDRESSING_STYLE = 'path'
# AWS_S3_CUSTOM_DOMAIN = f"{config('MINIO_BASE_URL')}:{config('MINIO_API_PORT')}/{AWS_STORAGE_BUCKET_NAME}"
# AWS_S3_URL_PROTOCOL = 'http:'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email teste console
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# EMAIL PRODUÇÃO
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = True
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = config('SERVER_EMAIL')


LOGOUT_REDIRECT_URL = 'index'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Configuração para tradução
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGES = (
    ('pt-br', 'Português'),
    ('en', 'English'),
)

# Recursos extras de segurança

# False para evitar potenciais loops de redirecionamento por conta do nginx.
SECURE_SSL_REDIRECT = False

# Habilita o HSTS (Strict Transport Security) apenas em produção.
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000  # 31536000 segundos = 1 ano
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG 

# Garante que os cookies de sessão e CSRF só sejam enviados via HTTPS em produção.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Estas podem ser mantidas como True em ambos os ambientes.
SECURE_CONTENT_TYPE_NOSNIFF = True
CSRF_COOKIE_HTTPONLY = True # Impede acesso ao cookie CSRF via JavaScript
X_FRAME_OPTIONS = 'DENY'

# Trocando o error para danger, para padronizar a cor no bootstrap
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  
}